defaults: &defaults
  email:
    notifications_sender: 'notifications@cortexcraft.com'
    devise_sender: 'support@cortexcraft.com'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults