defaults: &defaults
  email:
    notifications_sender: 'notifications@factspan.com'
    devise_sender: 'support@factspan.com'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults